---
- name : deploy web-application
  hosts: all
  become: true
  tasks:
    - name: install required packages
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip

    - name: install mysql packages
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - mysql-client

    - name: start mysql services
      service:
        name: mysql
        state: started
        enabled: yes
    - name: creating mysql database
      mysql_db: name= employee_db state= present

    - name: creating database user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: install python flask
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - flask
        - flask-mysql
    - name: copy source code file
      copy: src= /home/ansadmin/ansible dest= /opt/app.py

    - name: start web services
      shell: FLASK=/opt/app.py nohup flask run --host=0.0.0.0 &
